#!/usr/bin/env python3
"""
Flask web server to display emotion dashboard charts in browser.
Runs on Raspberry Pi to serve PNG charts generated by dashboard_per_user.py
"""

from flask import Flask, render_template, send_from_directory, jsonify, request
from flask_cors import CORS
import os
import sqlite3
from datetime import datetime, timedelta
import subprocess
import json
import sys

# Add src directory to path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'src'))
from wellbeing_advisor import WellbeingAdvisor

app = Flask(__name__)
CORS(app)  # Enable CORS for browser access

# Configuration
# Force DB to be in the same directory as this script (Project Root)
# This ensures both logger and server use the exact same file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.getenv('FER_DB', os.path.join(BASE_DIR, 'fer_events.db'))

print(f"Using Database at: {DB_PATH}")

DASHBOARD_DIR = os.path.join(BASE_DIR, 'dashboards')
# Use integrated dashboard that combines emotion + sensor data
DASHBOARD_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dashboard_integrated.py')

# Initialize Wellbeing Advisor
wellbeing_advisor = WellbeingAdvisor(db_path=DB_PATH)

def get_all_users():
    """Fetch list of all user IDs from database"""
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT DISTINCT user_id, COUNT(*) as event_count, 
                   MIN(ts_received) as first_seen, 
                   MAX(ts_received) as last_seen
            FROM events
            GROUP BY user_id
            ORDER BY last_seen DESC
        """)
        users = []
        for row in cursor.fetchall():
            users.append({
                'user_id': row[0],
                'event_count': row[1],
                'first_seen': row[2],
                'last_seen': row[3]
            })
        conn.close()
        return users
    except Exception as e:
        print(f"Error fetching users: {e}")
        return []

def find_best_user_match(requested_id):
    """Try to find a close matching user id in the database.
    - Return requested_id if it exists
    - Otherwise try suffix matching and return the most-recent user if found
    - Return None if no match
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()

        # Exact match first
        cur.execute("SELECT DISTINCT user_id FROM events WHERE user_id = ?", (requested_id,))
        row = cur.fetchone()
        if row:
            conn.close()
            return requested_id

        # Suffix match: use last segment after underscore or last 8 chars
        suffix = requested_id.split('_')[-1]

        # Look for any user_id that ends with the same suffix, pick most recent activity
        cur.execute("""
            SELECT user_id, MAX(ts_received) as last_seen
            FROM events
            WHERE user_id LIKE ? OR user_id LIKE ?
            GROUP BY user_id
            ORDER BY last_seen DESC
            LIMIT 1
        """, (f"%{suffix}", f"%{suffix[-8:]}"))
        row = cur.fetchone()
        conn.close()
        if row:
            return row[0]
    except Exception as e:
        print(f"Error in find_best_user_match: {e}")
    return None

def regenerate_dashboards():
    """Regenerate all dashboard charts (now uses integrated dashboard)"""
    try:
        # Run the INTEGRATED dashboard generator (emotion + sensor data)
        # This creates comprehensive mental-state reports with vitals
        result = subprocess.run(
            ['python3', DASHBOARD_SCRIPT, DB_PATH],
            cwd=BASE_DIR,
            capture_output=True,
            text=True,
            timeout=60
        )
        return {
            'success': result.returncode == 0,
            'stdout': result.stdout,
            'stderr': result.stderr
        }
    except Exception as e:
        return {
            'success': False,
            'error': str(e)
        }

@app.route('/')
def index():
    """Main dashboard page"""
    users = get_all_users()
    return render_template('dashboard.html', users=users)

@app.route('/api/users')
def api_users():
    """API endpoint to get list of users"""
    users = get_all_users()
    return jsonify(users)

@app.route('/api/regenerate', methods=['POST'])
def api_regenerate():
    """API endpoint to regenerate dashboards"""
    result = regenerate_dashboards()
    return jsonify(result)

@app.route('/api/debug')
def api_debug():
    """Debug endpoint to check DB status"""
    try:
        if not os.path.exists(DB_PATH):
            return jsonify({'error': 'DB file not found', 'path': DB_PATH})
            
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Get total count
        cursor.execute("SELECT COUNT(*) FROM events")
        total = cursor.fetchone()[0]
        
        # Get recent events
        cursor.execute("SELECT * FROM events ORDER BY id DESC LIMIT 5")
        recent = cursor.fetchall()
        
        # Get users
        cursor.execute("SELECT DISTINCT user_id FROM events")
        users = [r[0] for r in cursor.fetchall()]
        
        conn.close()
        
        return jsonify({
            'db_path': DB_PATH,
            'total_events': total,
            'user_count': len(users),
            'users': users,
            'recent_events': recent
        })
    except Exception as e:
        return jsonify({'error': str(e), 'path': DB_PATH})

@app.route('/dashboards/<path:filename>')
def serve_dashboard(filename):
    """Serve dashboard PNG files"""
    return send_from_directory(DASHBOARD_DIR, filename)

@app.route('/user/<user_id>')
def user_dashboard(user_id):
    """Display dashboard for specific user"""
    # Prefer exact folder, otherwise try to find a best match by suffix
    user_dir = os.path.join(DASHBOARD_DIR, user_id)
    displayed_user_id = user_id
    if not os.path.exists(user_dir):
        matched = find_best_user_match(user_id)
        if matched and matched != user_id:
            user_dir = os.path.join(DASHBOARD_DIR, matched)
            displayed_user_id = matched
        else:
            return f"No dashboard found for user {user_id}. Click 'Regenerate Dashboards' to create charts.", 404

    # Get list of chart files (including integrated sensor charts)
    charts = []
    chart_files = [
        'integrated_timeline.png',      # Integrated: HR + Emotions
        'hr_by_emotion.png',            # Integrated: HR distribution by emotion
        'spo2_timeline.png',            # Integrated: Blood oxygen
        'emotion_distribution.png',     # Original: Emotion counts
        'timeline.png',                 # Original: Emotion timeline
        'confidence.png',               # Original: Confidence
        'hourly_activity.png'           # Original: Activity by hour
    ]
    for chart_file in chart_files:
        chart_path = os.path.join(user_dir, chart_file)
        if os.path.exists(chart_path):
            charts.append({
                'name': chart_file.replace('.png', '').replace('_', ' ').title(),
                'url': f'/dashboards/{displayed_user_id}/{chart_file}'
            })

    # Read summary text if exists (contains wellbeing suggestions)
    summary_path = os.path.join(user_dir, 'summary.txt')
    summary = None
    if os.path.exists(summary_path):
        with open(summary_path, 'r') as f:
            summary = f.read()

    # If we matched to a different id, add a small notice
    if displayed_user_id != user_id:
        note = f"Note: showing data for '{displayed_user_id}' which closely matches your id '{user_id}'." \
               " If you believe this is incorrect, please contact the admin."
        summary = (note + '\n\n' + summary) if summary else note

    return render_template('user_dashboard.html', 
                          user_id=displayed_user_id, 
                          charts=charts, 
                          summary=summary)

@app.route('/api/user/<user_id>/summary')
def api_user_summary(user_id):
    """API endpoint to get user's dashboard data as JSON"""
    try:
        # Check if user exists in database
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT COUNT(*) as total, 
                   emotion,
                   AVG(confidence) as avg_conf,
                   MIN(ts_received) as first_seen,
                   MAX(ts_received) as last_seen
            FROM events 
            WHERE user_id = ?
            GROUP BY user_id, emotion
            ORDER BY total DESC
        """, (user_id,))
        
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            # Try to find a closely matching user id (suffix match)
            matched = find_best_user_match(user_id)
            if matched and matched != user_id:
                # re-run query for matched user
                conn = sqlite3.connect(DB_PATH)
                cursor = conn.cursor()
                cursor.execute("""
                    SELECT COUNT(*) as total, 
                           emotion,
                           AVG(confidence) as avg_conf,
                           MIN(ts_received) as first_seen,
                           MAX(ts_received) as last_seen
                    FROM events 
                    WHERE user_id = ?
                    GROUP BY user_id, emotion
                    ORDER BY total DESC
                """, (matched,))
                rows = cursor.fetchall()
                conn.close()
                # If still empty, return not found
                if not rows:
                    return jsonify({'error': 'User not found'}), 404
                # use matched id for response
                used_user_id = matched
            else:
                return jsonify({'error': 'User not found'}), 404
        else:
            used_user_id = user_id
        
        # Calculate stats
        total_events = sum(row[0] for row in rows)
        top_emotion = rows[0][1] if rows else 'Unknown'
        avg_confidence = int(sum(row[2] for row in rows) / len(rows))
        first_seen = rows[0][3]
        last_seen = rows[0][4]
        
        # Calculate days active
        from datetime import datetime
        try:
            first = datetime.fromisoformat(first_seen.replace('Z', '+00:00'))
            last = datetime.fromisoformat(last_seen.replace('Z', '+00:00'))
            days_active = max(1, (last - first).days + 1)
        except:
            days_active = 1
        
        # Check if charts exist
        user_dir = os.path.join(DASHBOARD_DIR, user_id)
        charts = []
        chart_files = ['emotion_distribution.png', 'timeline.png', 'confidence.png', 'hourly_activity.png']
        for chart_file in chart_files:
            chart_path = os.path.join(user_dir, chart_file)
            if os.path.exists(chart_path):
                charts.append({
                    'name': chart_file.replace('.png', '').replace('_', ' ').title(),
                    'url': f'/dashboards/{user_id}/{chart_file}'
                })
        
        # Read summary
        summary_path = os.path.join(user_dir, 'summary.txt')
        summary = None
        if os.path.exists(summary_path):
            with open(summary_path, 'r') as f:
                summary = f.read()
        
        return jsonify({
            'user_id': used_user_id,
            'stats': {
                'total_events': total_events,
                'top_emotion': top_emotion,
                'avg_confidence': avg_confidence,
                'days_active': days_active
            },
            'charts': charts,
            'summary': summary
        })
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/user/<user_id>/wellbeing')
def api_user_wellbeing(user_id):
    """API endpoint to get personalized context-aware wellbeing suggestions"""
    try:
        # Generate comprehensive wellbeing report
        report = wellbeing_advisor.generate_wellbeing_report(user_id)
        return jsonify(report)
        
    except Exception as e:
        return jsonify({'error': str(e), 'status': 'error'}), 500

# === WebApp Routes ===

@app.route('/camera')
def camera_app():
    """Serve the camera app (index.html)"""
    return send_from_directory('webapp', 'index.html')

@app.route('/my-dashboard')
def my_dashboard_app():
    """Serve the personal dashboard app (dashboard.html)"""
    return send_from_directory('webapp', 'dashboard.html')

@app.route('/<path:filename>')
def serve_webapp_static(filename):
    """Serve static files from webapp directory"""
    # Check if file exists in webapp
    if os.path.exists(os.path.join('webapp', filename)):
        return send_from_directory('webapp', filename)
    return "File not found", 404

import threading
import time

# ... existing code ...

def background_regenerator():
    """Regenerate dashboards every 2 minutes in the background"""
    while True:
        print(f"[{datetime.now()}] Regenerating dashboards...")
        result = regenerate_dashboards()
        if not result.get('success', False):
            error_msg = result.get('stderr', result.get('error', 'Unknown error'))
            print(f"❌ Dashboard generation failed:\n{error_msg}")
        else:
            print(f"✅ Dashboards updated successfully")
        time.sleep(120)

if __name__ == '__main__':
    # Create dashboards directory if it doesn't exist
    os.makedirs(DASHBOARD_DIR, exist_ok=True)
    
    # Start background thread for dashboard generation
    thread = threading.Thread(target=background_regenerator, daemon=True)
    thread.start()
    
    print(f"Dashboard Server Starting...")
    print(f"Database: {DB_PATH}")
    print(f"Dashboard Directory: {DASHBOARD_DIR}")
    print(f"Access at: http://<raspberry-pi-ip>:5000")
    
    # Run Flask server
    app.run(host='0.0.0.0', port=5000, debug=False)
