#!/usr/bin/env python3
"""
Flask web server to display emotion dashboard charts in browser.
Runs on Raspberry Pi to serve PNG charts generated by dashboard_per_user.py
"""

from flask import Flask, render_template, send_from_directory, jsonify, request
from flask_cors import CORS
import os
import sqlite3
from datetime import datetime, timedelta
import subprocess
import json

app = Flask(__name__)
CORS(app)  # Enable CORS for browser access

# Configuration
DB_PATH = os.getenv('FER_DB', '/home/pi/fer_events.db')
DASHBOARD_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dashboards')
DASHBOARD_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dashboard_per_user.py')

def get_all_users():
    """Fetch list of all user IDs from database"""
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT DISTINCT user_id, COUNT(*) as event_count, 
                   MIN(ts_received) as first_seen, 
                   MAX(ts_received) as last_seen
            FROM events
            GROUP BY user_id
            ORDER BY last_seen DESC
        """)
        users = []
        for row in cursor.fetchall():
            users.append({
                'user_id': row[0],
                'event_count': row[1],
                'first_seen': row[2],
                'last_seen': row[3]
            })
        conn.close()
        return users
    except Exception as e:
        print(f"Error fetching users: {e}")
        return []

def regenerate_dashboards():
    """Regenerate all dashboard charts"""
    try:
        result = subprocess.run(
            ['python3', DASHBOARD_SCRIPT, DB_PATH],
            capture_output=True,
            text=True,
            timeout=60
        )
        return {
            'success': result.returncode == 0,
            'stdout': result.stdout,
            'stderr': result.stderr
        }
    except Exception as e:
        return {
            'success': False,
            'error': str(e)
        }

@app.route('/')
def index():
    """Main dashboard page"""
    users = get_all_users()
    return render_template('dashboard.html', users=users)

@app.route('/api/users')
def api_users():
    """API endpoint to get list of users"""
    users = get_all_users()
    return jsonify(users)

@app.route('/api/regenerate', methods=['POST'])
def api_regenerate():
    """API endpoint to regenerate dashboards"""
    result = regenerate_dashboards()
    return jsonify(result)

@app.route('/dashboards/<path:filename>')
def serve_dashboard(filename):
    """Serve dashboard PNG files"""
    return send_from_directory(DASHBOARD_DIR, filename)

@app.route('/user/<user_id>')
def user_dashboard(user_id):
    """Display dashboard for specific user"""
    # Check if user directory exists
    user_dir = os.path.join(DASHBOARD_DIR, user_id)
    if not os.path.exists(user_dir):
        return f"No dashboard found for user {user_id}. Click 'Regenerate Dashboards' to create charts.", 404
    
    # Get list of chart files
    charts = []
    chart_files = ['emotion_distribution.png', 'timeline.png', 'confidence.png', 'hourly_activity.png']
    for chart_file in chart_files:
        chart_path = os.path.join(user_dir, chart_file)
        if os.path.exists(chart_path):
            charts.append({
                'name': chart_file.replace('.png', '').replace('_', ' ').title(),
                'url': f'/dashboards/{user_id}/{chart_file}'
            })
    
    # Read summary text if exists
    summary_path = os.path.join(user_dir, 'summary.txt')
    summary = None
    if os.path.exists(summary_path):
        with open(summary_path, 'r') as f:
            summary = f.read()
    
    return render_template('user_dashboard.html', 
                          user_id=user_id, 
                          charts=charts, 
                          summary=summary)

@app.route('/api/user/<user_id>/summary')
def api_user_summary(user_id):
    """API endpoint to get user's dashboard data as JSON"""
    try:
        # Check if user exists in database
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT COUNT(*) as total, 
                   emotion,
                   AVG(confidence) as avg_conf,
                   MIN(ts_received) as first_seen,
                   MAX(ts_received) as last_seen
            FROM events 
            WHERE user_id = ?
            GROUP BY user_id, emotion
            ORDER BY total DESC
        """, (user_id,))
        
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            return jsonify({'error': 'User not found'}), 404
        
        # Calculate stats
        total_events = sum(row[0] for row in rows)
        top_emotion = rows[0][1] if rows else 'Unknown'
        avg_confidence = int(sum(row[2] for row in rows) / len(rows))
        first_seen = rows[0][3]
        last_seen = rows[0][4]
        
        # Calculate days active
        from datetime import datetime
        try:
            first = datetime.fromisoformat(first_seen.replace('Z', '+00:00'))
            last = datetime.fromisoformat(last_seen.replace('Z', '+00:00'))
            days_active = max(1, (last - first).days + 1)
        except:
            days_active = 1
        
        # Check if charts exist
        user_dir = os.path.join(DASHBOARD_DIR, user_id)
        charts = []
        chart_files = ['emotion_distribution.png', 'timeline.png', 'confidence.png', 'hourly_activity.png']
        for chart_file in chart_files:
            chart_path = os.path.join(user_dir, chart_file)
            if os.path.exists(chart_path):
                charts.append({
                    'name': chart_file.replace('.png', '').replace('_', ' ').title(),
                    'url': f'/dashboards/{user_id}/{chart_file}'
                })
        
        # Read summary
        summary_path = os.path.join(user_dir, 'summary.txt')
        summary = None
        if os.path.exists(summary_path):
            with open(summary_path, 'r') as f:
                summary = f.read()
        
        return jsonify({
            'user_id': user_id,
            'stats': {
                'total_events': total_events,
                'top_emotion': top_emotion,
                'avg_confidence': avg_confidence,
                'days_active': days_active
            },
            'charts': charts,
            'summary': summary
        })
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Create dashboards directory if it doesn't exist
    os.makedirs(DASHBOARD_DIR, exist_ok=True)
    
    print(f"Dashboard Server Starting...")
    print(f"Database: {DB_PATH}")
    print(f"Dashboard Directory: {DASHBOARD_DIR}")
    print(f"Access at: http://<raspberry-pi-ip>:5000")
    
    # Run Flask server
    app.run(host='0.0.0.0', port=5000, debug=False)
